[project]
name = "walnut"
description = "Read or write a BBrowser study"
version = "0.1.0"
authors = [
    { name = "Tri Le", email = "tri@bioturing.com" },
    { name = "Vu Nguyen", email = "vu@bioturing.com" }
]
dependencies = [
    "pydantic"
]

[project.optional-dependencies]
dev = [
]
