[tool.poetry]
name = "walnut"
version = "0.1.0"
description = "Read or write a BBrowser study"
authors = [
    "Tri Le <tri@bioturing.com>",
    "Vu Nguyen <vu@bioturing.com>"
]
license = "LICENSE"
readme = "README.md"
classifiers = [
    "Programming Language :: Python",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
include = [ "*.db" ]

[tool.poetry.dependencies]

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"