[tool.poetry]
name = "walnut"
version = "0.1.0"
description = "Read or write a BBrowser study"
authors = [
    "Tri Le <tri@bioturing.com>",
    "Vu Nguyen <vu@bioturing.com>",
    "Hao Tran <hao@bioturing.com>"
]
license = "LICENSE"
readme = "README.md"
classifiers = [
    "Programming Language :: Python",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
include = [ "*.db" ]

[tool.poetry.dependencies]
anyio="3.5.0"
certifi="2021.10.8"
charset-normalizer="2.0.12"
fastapi="0.75.2"
h5py="3.6.0"
idna="3.3"
numpy="1.22.3"
pycryptodome="3.14.1"
pydantic="1.9.0"
requests="2.27.1"
sniffio="1.2.0"
starlette="0.17.1"
typing_extensions="4.2.0"
urllib3="1.26.9"

[tool.poetry.dev-dependencies]
pytest = "7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
